# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5a31e298c71c4fd8da084c60b9b6ad05bc969456d5d19adb6e82b11679a3da47d0c938ddd2488011fdac4352510fe3671ff78950feba0a284b9ba6d681a57e2

test:
  secret_key_base: f6558caedd8bd7ddec781620da03afd81e33c89a58e7e97ecfac033f6b76240ac526c255c27180e91b77afb70ff62d16060a485af0c7f10248c88218e1fa3702

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
